name: "ReconOS"
description: "Operating System for Reconfigurable Computing"

url: http://reconos.de

pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "tables", "with_toc_data"]
